### ISSUE TITLE
Bug Error js 

### ISSUE THREAD

**Issue by Aysmow** [Simpleboy353/REAPER-2.0#106]
![image](https://user-images.githubusercontent.com/74377244/140339141-cf217c0c-00e8-4d9d-95c4-5b26fa7d409c.png)

**Comment by Simpleboy353** [comment]
try doing npm install

**Comment by Aysmow** [comment]
still not

**Comment by LeoMavri** [comment]
Did you update Node recently ? If yes, revert to the old version.

**Comment by Aysmow** [comment]
> Did you update Node recently ? If yes, revert to the old version.

Which version?

**Comment by Aysmow** [comment]
Which version?

>

**Comment by LeoMavri** [comment]
> > Did you update Node recently ? If yes, revert to the old version.
> 
> Which version?

That's the question you have to answer yourself, can't physically see what you used before upgrading. What's your node version ?

```
node -v
```

In any cmd^

**Comment by Simpleboy353** [comment]
Seems like you have nodejs v17, can you ahift back to an older version like v16.10.0 or v16.11.0
