### ISSUE TITLE
big player bug

### ISSUE THREAD

**Issue by 1stminhcar** [Simpleboy353/REAPER-2.0#112]
proof is on ur discord server

**Comment by Natesplanet** [comment]
I am not in his discord server cuz i forgot to join on my main account :trollface: So can u send the proof here and the bug?

**Comment by Simpleboy353** [comment]
If you have joined the server, I suggest you to report the bug in the server

**Comment by 1stminhcar** [comment]
can u even attach smth here?

**Comment by 1stminhcar** [comment]
> 
> 
> If you have joined the server, I suggest you to report the bug in the server

u know it
but how to fix
