### ISSUE TITLE
!help for Fun has errors and I don't know how to fix it 😞 

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#114]
![image](https://user-images.githubusercontent.com/92893096/141141168-88df781b-79a4-485e-91fe-02e3c3b7d32c.png)

I am not the "professional coder" so I am not sure how to fix this. If anyone can help fix this it would be nice!

**Comment by Simpleboy353** [comment]
![Screenshot_2021_1110_205742](https://user-images.githubusercontent.com/67364262/141141937-f1d68e53-b491-4cd3-af0e-c45260d97195.jpg)

Go to events > interactions > menu > help.js
Make this change to the file

**Comment by Natesplanet** [comment]
ok

**Comment by Natesplanet** [comment]
it works :)
