### ISSUE TITLE
DM Command Not Working

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#115]
![image](https://user-images.githubusercontent.com/92893096/141198354-0211e957-243a-4aa8-a202-9cdaf0c62c60.png)
![image](https://user-images.githubusercontent.com/92893096/141198396-0089b6df-c9ff-43b3-ad61-79d8952998e1.png)

I know that this command is disabled but why and can I just enable it again by deleting
`return message.channel.send(
        "the Command has been disabled because of facing crash issues"`

and

by changing disable to enable?

`const state = "disabled";
    if (state === "disabled") {`

**Comment by feday977** [comment]
hi bro , The "if" instruction checks the constant state if it is disabled and return you this msg. 
Just change the constant state like this :

const state = "ahahah";

**Comment by Natesplanet** [comment]
Will the command then work?

**Comment by 1KxDipsy** [comment]
yes , dm me in discord 1KxDIPSY#0001 i can help you

**Comment by Natesplanet** [comment]
Check your Discord Tag again

**Comment by 1KxDipsy** [comment]
its okey

**Comment by Natesplanet** [comment]
@1KxDipsy  Showed me how to fix it
