### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by SrPeterr** [Simpleboy353/REAPER-2.0#120]
Hi!
Im getting this error...
I just forked the repo, cloned it, did `npm install` and then `node .`

![image](https://user-images.githubusercontent.com/21348463/141556277-82870c07-9a72-40e9-a83a-7b5044231044.png)

**Comment by Simpleboy353** [comment]
You need to install nodejs v16.6 or higher

**Comment by Simpleboy353** [comment]
I would recommend using node version 16.10.0 or 16.11.0

**Comment by SrPeterr** [comment]
That worked! But now Im getting another error :( I have python installed...

![image](https://user-images.githubusercontent.com/21348463/141620499-ee04d214-c465-466f-80c1-a5eaa9055682.png)

**Comment by Simpleboy353** [comment]
You can try:

1). Delete the `node_modules` folder and the `package-lock.json` file. Delete `package-lock.json` file and not `package.json`

2). Open Powershell with Admin perms and then run `npm install --global-windows-build-tools`

3). Then open Visual Studio Code or your code editor again and do `npm install` in terminal to re-install the required dependencies.

This should probably fix this error.
