### ISSUE TITLE
Dotenv?

### ISSUE THREAD

**Issue by StudNastty** [Simpleboy353/REAPER-2.0#122]
No src file or .env
![Error](https://user-images.githubusercontent.com/49431954/141653451-d75e6190-25dc-4990-8966-4a01b2a98151.PNG)

**Comment by Simpleboy353** [comment]
remove first line from index.js file

**Comment by StudNastty** [comment]
i figured but just wanted to make sure you were aware the issue, since its straight from the github

**Comment by Simpleboy353** [comment]
oh ok
