### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by StudNastty** [Simpleboy353/REAPER-2.0#124]
ERROR][ERR_LOG][16-11-2021, 20:09:13 pm]: Status code: 410
[ERROR][ERR_LOG][16-11-2021, 20:09:14 pm]: [PlayerError] Cannot play a resource that has already ended

started having this issue today worked fine before today kinda wierd ```Just looking for support or if anyone else has this issue```

**Comment by Simpleboy353** [comment]
Issue goes away on restarting or when trying to play a different song. Also, no help can be provided for this as this error is related to the package `ytdl-core`

**Comment by StudNastty** [comment]
Didnt fix on restart or different song but fixed after like a hour
