### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#125]
Hello, I have a question 

How would you merge both of these Repositories together

https://github.com/Simpleboy353/Tickets-Bot
And My Reaper
https://github.com/Natesplanet/N-Bot

**Comment by 1stminhcar** [comment]
downlooad the file then reupload it:>

**Comment by Natesplanet** [comment]
On what?

**Comment by Simpleboy353** [comment]
Issues relating merging can be solved on our discord server only
