### ISSUE TITLE
error log channel

### ISSUE THREAD

**Issue by nightmxre69** [Simpleboy353/REAPER-2.0#13]
um hey!
what am I supposed to do with the ERROR_LOGS_CHANNEL in the config.json?

**Comment by Simpleboy353** [comment]
> um hey!
> what am I supposed to do with the ERROR_LOGS_CHANNEL in the config.json?

You need to add a channel ID here. This is the channel where the errors will be logged!

**Comment by nightmxre69** [comment]
so like I need to make a separate server, make an error-log channel, and paste that channel's ID?

**Comment by Simpleboy353** [comment]
> so like I need to make a separate server, make an error-log channel, and paste that channel's ID?

Its upto you. You can choose any channel or server of your choice.

**Comment by nightmxre69** [comment]
aight thanks!

**Comment by Simpleboy353** [comment]
Glad to help you!
