### ISSUE TITLE
Uncaught Exception: client is not defined

### ISSUE THREAD

**Issue by CherryWaffle** [Simpleboy353/REAPER-2.0#131]
I'm getting this error `ERR_REQUIRE_ESM` for the chalk package..

**Comment by Simpleboy353** [comment]
can you try reverting back to an older version of `chalk`

**Comment by CherryWaffle** [comment]
It says its a problem with `node-fetch`

**Comment by Simpleboy353** [comment]
How to fix `Error [ERR_REQUIRE_ESM]: require() of ESM module` ?

- Go to your package.json file

- Replace `node-fetch: "^3.0.0" ` with `node-fetch: "^2.6.1" `

- Reinstall node-fetch by doing `npm install node-fetch@2.6.1`

- Restart the bot

^^ This should probably fix the error and your bot should start to work normally.

**Comment by CherryWaffle** [comment]
The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.

**Comment by CherryWaffle** [comment]
I did make a few changes, but it wont work for some reason ..

**Comment by Rahuletto** [comment]
> The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.

Full error please ?

**Comment by Emiluvik** [comment]
> > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> 
> Full error please ?

This is the full error, for me at least...
https://imgur.com/a/VrbNJYK

**Comment by 1stminhcar** [comment]
find the line that require client and if it was above the const slient or not

**Comment by Shaham99** [comment]
> The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.

I got this same error hoe to fix this?

**Comment by Rahuletto** [comment]
> > > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> > 
> > Full error please ?
> 
> This is the full error, for me at least...
> https://imgur.com/a/VrbNJYK
> 
> 

Full error means to show the console. It's just one line. Bruh

**Comment by Simpleboy353** [comment]
> > > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> > 
> > 
> > Full error please ?
> 
> This is the full error, for me at least... https://imgur.com/a/VrbNJYK

Go to the `index.js` file and change the code (line 73 to line 81) to comments, and then run the bot again. This will help you to log the full error in the console.

**Comment by Emiluvik** [comment]
> > > > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> > > 
> > > 
> > > Full error please ?
> > 
> > 
> > This is the full error, for me at least... https://imgur.com/a/VrbNJYK
> 
> Go to the `index.js` file and change the code (line 73 to line 81) to comments, and then run the bot again. This will help you to log the full error in the console.

That works, thanks!

**Comment by Emiluvik** [comment]
> > > > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> > > 
> > > 
> > > Full error please ?
> > 
> > 
> > This is the full error, for me at least...
> > https://imgur.com/a/VrbNJYK
> 
> Full error means to show the console. It's just one line. Bruh

THIS is the full error. https://imgur.com/a/pNQ2xLI

**Comment by Simpleboy353** [comment]
> The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.

Error Fixed. Updated your `ready.js` event file.

**Comment by Emiluvik** [comment]
> > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> 
> Error Fixed. Update your `ready.js` event file.

It did work... A little bit, now I get a new error. https://imgur.com/a/cnl195u

**Comment by Simpleboy353** [comment]
> > > The bot now starts, but I get this error `Uncaught Exception: ReferenceError: client is not defined` and the bot wont respond to commands.
> > 
> > 
> > Error Fixed. Update your `ready.js` event file.
> 
> It did work... A little bit, now I get a new error. https://imgur.com/a/cnl195u

Fixed. Should work now.
