### ISSUE TITLE
client.login

### ISSUE THREAD

**Issue by brahmendra79** [Simpleboy353/REAPER-2.0#139]
It Saying That All Commands Loaded But At Last Its Not Saying ${Client.user.username} is Online! In Console

And My Bot Is In Offline

**Comment by brahmendra79** [comment]
Client is ready
File ban.js was loaded
File ascii.js was loaded
File catsay.js was loaded
File dab.js was loaded
File emoji.js was loaded
File gif.js was loaded
File hack.js was loaded
File hug.js was loaded
File joke.js was loaded
File kill.js was loaded
File meme.js was loaded
File nitro.js was loaded
File pokeimg.js was loaded
File reverse.js was loaded
File roast.js was loaded
File football.js was loaded
File botserver.js was loaded
File eval.js was loaded
File dm.js was loaded
File kick.js was loaded
File covid.js was loaded
File hello.js was loaded
File user.js was loaded 


until here it is showing but there is not ${Client.user.username} is Online! In Console

**Comment by Simpleboy353** [comment]
any error shown in console?
