### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by nightmxre69** [Simpleboy353/REAPER-2.0#14]
uhh its weird
i stopped the bot with `^C` in the console
then started it with `node index.js`
then i ran a command, the bot replied twice
stopped, and ran the bot again
this time the bot is replying 3 times,

the last time i made a bot the same issue occured

what could be the issue?

**Comment by Simpleboy353** [comment]
> uhh its weird
> i stopped the bot with `^C` in the console
> then started it with `node index.js`
> then i ran a command, the bot replied twice
> stopped, and ran the bot again
> this time the bot is replying 3 times,
> 
> the last time i made a bot the same issue occured
> 
> what could be the issue?

It could be happening because of multiple terminals running together. Please make sure there is only one terminal running at a time.

**Comment by nightmxre69** [comment]
oh so that's the case
i'll try with closing all terminals and let u know

**Comment by nightmxre69** [comment]
aight it's working thanks again
