### ISSUE TITLE
How can I use a command in the bot's dm? 

### ISSUE THREAD

**Issue by fomundifr** [Simpleboy353/REAPER-2.0#142]
Goodnight 

I am using this model to make my bot but I need that if someone uses a command within the bot's dm, the bot will send what the user is asking for, but I don't know how to do it, thank you very much

**Comment by Simpleboy353** [comment]
set `guildOnly` to `false` in the respective commands

**Comment by fomundifr** [comment]
And that in which file is it?

**Comment by fomundifr** [comment]
And how can I do it but with interactions?
