### ISSUE TITLE
AlexFlipnote API token is no longer a thing

### ISSUE THREAD

**Issue by vitalkanev** [Simpleboy353/REAPER-2.0#143]
Please be noted that AlexFlipnote has [deprecated API tokens and some endpoints](https://discord.com/channels/86484642730885120/634727022634991627/919355036239274075) (Requires you to [join Alex's Discord server](https://discord.gg/DpxkY3x)). The issue also affects this repository.

By looking at the repository code, it appears that none of the endpoints (`achievement`, `amiajoke`, `bad`, `challenge`, `facts`, `p******`, `scroll`, `supreme` and `trash`) are supported by Alex anymore, only some basic endpoints like `color`, `dog`, `birb`, `cat` and such.

What this means? Either remove these commands entirely or find another that supports such features. I bet on the first option because I might submit a PR that removes these commands ~~or converts them into a dummy thing~~.

**Comment by DPG896** [comment]
ye

**Comment by Simpleboy353** [comment]
Yeah ik, i am searching for a new api now and if not found I',ll probably remove these commands.

**Comment by Simpleboy353** [comment]
If you wanna continue, move to discussions
