### ISSUE TITLE
const chalk = require("chalk");

### ISSUE THREAD

**Issue by CrazyGladiator** [Simpleboy353/REAPER-2.0#144]
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/container/node_modules/chalk/source/index.js from /home/container/index.js not supported.
Instead change the require of /home/container/node_modules/chalk/source/index.js in /home/container/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/container/index.js:2:15) {
  code: 'ERR_REQUIRE_ESM'

**Comment by Simpleboy353** [comment]
How to fix Error [ERR_REQUIRE_ESM]: require() of ESM module ?

Go to your package.json file

Replace node-fetch: "^3.0.0"  with node-fetch: "^2.6.1" 

Reinstall node-fetch by doing npm install node-fetch@2.6.1

Restart the bot

^^ This should probably fix the error and your bot should start to work normally.

**Comment by Simpleboy353** [comment]
How to fix `Error [ERR_REQUIRE_ESM]: require()` for the package chalk ?

Uninstall the package `chalk`

Do npm install `chalk@4.1.0`

^^ This should probably fix the error and your bot should start to work normally.
