### ISSUE TITLE
better-sqlite3 err

### ISSUE THREAD

**Issue by ParTy-Play-go** [Simpleboy353/REAPER-2.0#149]
Error: The module '/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 93. This version of Node.js requires NODE_MODULE_VERSION 102. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).

**Comment by Simpleboy353** [comment]
try doing |npm install` in console
