### ISSUE TITLE
Some Commands Disabled

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#151]
I have some issues with some images command and I am guessing this is because of the AlexFlipnote API key. So how can I fix this issue?
![image](https://user-images.githubusercontent.com/92893096/149351980-0eb8cd4e-bcd0-476a-b64f-e06be9175578.png)
![image](https://user-images.githubusercontent.com/92893096/149351992-a5ddc1ac-4391-43df-adaa-97f6613ab573.png)

**Comment by Simpleboy353** [comment]
Read the latest update logs. That will help you get your answer.
