### ISSUE TITLE
Issue with Reaper when starting on Replit

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#158]
When I start Reaper on Replit I keep on getting this issue when doing node index
Someone Please help 🥺 🙏 

```
 node index
/home/runner/NBot/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/NBot/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
 
```

**Comment by Natesplanet** [comment]
@Simpleboy353 Please help 🙏 🥺

**Comment by demauye** [comment]
Regenerate your bot token and add the new token to the config.json file

**Comment by Simpleboy353** [comment]
> When I start Reaper on Replit I keep on getting this issue when doing node index Someone Please help 🥺 🙏
> 
> ```
>  node index
> /home/runner/NBot/node_modules/discord.js/src/rest/RESTManager.js:32
>     const token = this.client.token ?? this.client.accessToken;
>                                      ^
> 
> SyntaxError: Unexpected token '?'
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/runner/NBot/node_modules/discord.js/src/client/BaseClient.js:4:21)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>  
> ```

You need to update node to v16 in replit, follow these instructions:

How to fix the `Unexpected Token "?" `error?

- If you are using an online IDE like repl.it to run the bot, in the Shell, run this command:
```js
npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH 
```

- If you are trying to run the bot using VS Code terminal or some other Code Editor terminal, then visit https://nodejs.org and download the latest version of nodejs (v16).

**Comment by Natesplanet** [comment]
Still won't work 😢

**Comment by Simpleboy353** [comment]
where did you run this code?

**Comment by Natesplanet** [comment]
On Replit

**Comment by Natesplanet** [comment]
I can share the link so you can edit my replit if u want

**Comment by Simpleboy353** [comment]
Share in dms in discord

**Comment by Natesplanet** [comment]
I just did

**Comment by Natesplanet** [comment]
I sent the Replit link to your discord
