### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by ClaudioPanConQueso** [Simpleboy353/REAPER-2.0#16]
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'mongoose'
Require stack:
- C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\si\\Downloads\\REAPER-2.0-6.3.0-stable\\REAPER-2.0-6.3.0-stable\\index.js'
  ]
}

when i put "NPM INSTALL MONGOOSE" it gives me error

npm ERR! code 1
npm ERR! path C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@16.4.0 | win32 | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.4.0 | win32 | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Users\si\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/node-v16.4.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/node-v16.4.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/SHASUMS256.txt
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/win-x64/node.lib
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\si\\Downloads\\REAPER-2.0-6.3.0-stable\\REAPER-2.0-6.3.0-stable\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\si\\Downloads\\REAPER-2.0-6.3.0-stable\\REAPER-2.0-6.3.0-stable\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas
npm ERR! gyp ERR! node -v v16.4.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)       
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19041
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\si\\Downloads\\REAPER-2.0-6.3.0-stable\\REAPER-2.0-6.3.0-stable\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v16.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

srry, i don't know about coding

**Comment by Simpleboy353** [comment]
> node:internal/modules/cjs/loader:930
> throw err;
> ^
> 
> Error: Cannot find module 'mongoose'
> Require stack:
> 
> * C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\index.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:772:27)
>   at Module.require (node:internal/modules/cjs/loader:999:19)
>   at require (node:internal/modules/cjs/helpers:93:18)
>   at Object. (C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\index.js:11:18)
>   at Module._compile (node:internal/modules/cjs/loader:1095:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
>   at Module.load (node:internal/modules/cjs/loader:975:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:816:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   'C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\index.js'
>   ]
>   }
> 
> when i put "NPM INSTALL MONGOOSE" it gives me error
> 
> npm ERR! code 1
> npm ERR! path C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
> npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
> npm ERR! node-pre-gyp info it worked if it ends with ok
> npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
> npm ERR! node-pre-gyp info using node@16.4.0 | win32 | x64
> npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
> npm ERR! node-pre-gyp info check checked for "C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node" (not found)
> npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
> npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
> npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
> npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
> npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@7.1.2
> npm ERR! gyp info using node@16.4.0 | win32 | x64
> npm ERR! gyp info ok
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@7.1.2
> npm ERR! gyp info using node@16.4.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Users\si\AppData\Local\Programs\Python\Python39\python.exe"
> npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/node-v16.4.0-headers.tar.gz
> npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/node-v16.4.0-headers.tar.gz
> npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/SHASUMS256.txt
> npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/win-x86/node.lib
> npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/win-x64/node.lib
> npm ERR! gyp http GET https://nodejs.org/download/release/v16.4.0/win-arm64/node.lib
> npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/SHASUMS256.txt
> npm ERR! gyp http 404 https://nodejs.org/download/release/v16.4.0/win-arm64/node.lib
> npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/win-x86/node.lib
> npm ERR! gyp http 200 https://nodejs.org/download/release/v16.4.0/win-x64/node.lib
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
> npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
> npm ERR! gyp ERR! find VS looking for Visual Studio 2015
> npm ERR! gyp ERR! find VS - not found
> npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> npm ERR! gyp ERR! find VS For more information consult the documentation at:
> npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> npm ERR! gyp ERR! stack at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
> npm ERR! gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
> npm ERR! gyp ERR! stack at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
> npm ERR! gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
> npm ERR! gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
> npm ERR! gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
> npm ERR! gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
> npm ERR! gyp ERR! stack at ChildProcess.exithandler (node:child_process:404:5)
> npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:394:28)
> npm ERR! gyp ERR! stack at maybeClose (node:internal/child_process:1067:16)
> npm ERR! gyp ERR! System Windows_NT 10.0.19041
> npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node" "--module_name=canvas" "--module_path=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
> npm ERR! gyp ERR! cwd C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas
> npm ERR! gyp ERR! node -v v16.4.0
> npm ERR! gyp ERR! node-gyp -v v7.1.2
> npm ERR! gyp ERR! not ok
> npm ERR! node-pre-gyp ERR! build error
> npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
> npm ERR! node-pre-gyp ERR! stack at ChildProcess. (C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:394:28)
> npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1067:16)
> npm ERR! node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
> npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19041
> npm ERR! node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
> npm ERR! node-pre-gyp ERR! cwd C:\Users\si\Downloads\REAPER-2.0-6.3.0-stable\REAPER-2.0-6.3.0-stable\node_modules\canvas
> npm ERR! node-pre-gyp ERR! node -v v16.4.0
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> npm ERR! node-pre-gyp ERR! not ok
> 
> srry, i don't know about coding

Please refer to this [page](https://stackoverflow.com/questions/57541402/node-gyp-configure-got-gyp-err-find-vs#:~:text=Open%20your%20Visual%20Studio%20%26%20then,Hope%20this%20helps.&text=It%20is%20because%20that%20the,tools%20in%20visual%20studio%20installer)

**Comment by ClaudioPanConQueso** [comment]
still i have error
but a differrent error

**Comment by Simpleboy353** [comment]
What error?

**Comment by ClaudioPanConQueso** [comment]
hello, i don't know which error, but i deleted files, i will not code my bot because i'm coding in SCPSL Plugins. 
sorry
