### ISSUE TITLE
Slash commands error

### ISSUE THREAD

**Issue by Littleclaws-alt** [Simpleboy353/REAPER-2.0#193]
If I do a slash command, discord returns a "the application did not respond" error message. In console it says this: 
![Screenshot_20220724-162337-755](https://user-images.githubusercontent.com/107492686/180670147-72b90e7f-8583-489b-969f-bd8648d13f23.png)
Ps, im on replit on mobile rn.

**Comment by Simpleboy353** [comment]
Issue fixed in new version
