### ISSUE TITLE
Some commands do not work or do not work correctly

### ISSUE THREAD

**Issue by makarasty** [Simpleboy353/REAPER-2.0#195]
I got into the voice channel beforehand
![изображение](https://user-images.githubusercontent.com/71918286/185369152-114aecdd-bdd5-4363-937c-fb4346432c90.png)

![изображение](https://user-images.githubusercontent.com/71918286/185369307-485d1450-6146-4494-a788-d25ab42694be.png)

![изображение](https://user-images.githubusercontent.com/71918286/185369376-17a2d1aa-6c90-4ad4-aea9-b6382f9762a1.png)

...

the text is not green
![изображение](https://user-images.githubusercontent.com/71918286/185369910-3beaa686-474e-43dd-ba35-0e430762954f.png)

![изображение](https://user-images.githubusercontent.com/71918286/185370386-73bd3afc-a4f7-42c1-8c18-5953189f5821.png)

![изображение](https://user-images.githubusercontent.com/71918286/185370683-2b43c768-c046-4980-b1bf-465f30296240.png)

![изображение](https://user-images.githubusercontent.com/71918286/185370793-28d4ce53-2477-4696-b39f-d901c29d9497.png)

no errors in the console
![ScreenShot_20220818131409](https://user-images.githubusercontent.com/71918286/185371083-f369ac4d-6fbd-4eef-9830-84e2f997e55b.png)

![изображение](https://user-images.githubusercontent.com/71918286/185371406-62078771-7260-4c0f-b9cc-c61981a66b79.png)

=alert doesn't work

![изображение](https://user-images.githubusercontent.com/71918286/185372015-32c1d662-f940-491e-9275-df2b1a647d70.png)

=biden doesn't work

=dockofshame doesn't work

![изображение](https://user-images.githubusercontent.com/71918286/185372830-55172d3b-f816-45c5-9450-bafac06d060c.png)

file won't open
![изображение](https://user-images.githubusercontent.com/71918286/185373007-f0f4d898-a5e8-4199-bacf-a77d58136ed3.png)

![изображение](https://user-images.githubusercontent.com/71918286/185373248-4b2473c8-3123-4791-876e-28c9a7d82c07.png)

file won't open
![изображение](https://user-images.githubusercontent.com/71918286/185373319-3760b404-3fff-4cef-b2d8-59a7e2e1b72e.png)

![изображение](https://user-images.githubusercontent.com/71918286/185373500-37752595-00c7-44fb-9c8f-6dde71fa3f7e.png)

![изображение](https://user-images.githubusercontent.com/71918286/185373703-d2dfa9bd-29b0-4f53-97c3-dfd91ef7c5e6.png)

![изображение](https://user-images.githubusercontent.com/71918286/185373789-c485d9bb-856e-4fa6-aa9a-69262fb861f6.png)

![изображение](https://user-images.githubusercontent.com/71918286/185373869-7f9e9699-569c-4941-9611-612306b9c84d.png)

=policy doesn't work

=report doesn't work

=userinfo doesn't work

=userid doesn't work

=serverinfo doesn't work

=suggest doesn't work

music work 50/50

bot version in package.json "version": "v8.0.0"

and many other things, maybe I just use an old version of the bot, it seems to me that the bot does not work with discord 14

**Comment by Simpleboy353** [comment]
> I got into the voice channel beforehand ![изображение](https://user-images.githubusercontent.com/71918286/185369152-114aecdd-bdd5-4363-937c-fb4346432c90.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185369307-485d1450-6146-4494-a788-d25ab42694be.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185369376-17a2d1aa-6c90-4ad4-aea9-b6382f9762a1.png)
> 
> ...
> 
> the text is not green ![изображение](https://user-images.githubusercontent.com/71918286/185369910-3beaa686-474e-43dd-ba35-0e430762954f.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185370386-73bd3afc-a4f7-42c1-8c18-5953189f5821.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185370683-2b43c768-c046-4980-b1bf-465f30296240.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185370793-28d4ce53-2477-4696-b39f-d901c29d9497.png)
> 
> no errors in the console ![ScreenShot_20220818131409](https://user-images.githubusercontent.com/71918286/185371083-f369ac4d-6fbd-4eef-9830-84e2f997e55b.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185371406-62078771-7260-4c0f-b9cc-c61981a66b79.png)
> 
> =alert doesn't work
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185372015-32c1d662-f940-491e-9275-df2b1a647d70.png)
> 
> =biden doesn't work
> 
> =dockofshame doesn't work
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185372830-55172d3b-f816-45c5-9450-bafac06d060c.png)
> 
> file won't open ![изображение](https://user-images.githubusercontent.com/71918286/185373007-f0f4d898-a5e8-4199-bacf-a77d58136ed3.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185373248-4b2473c8-3123-4791-876e-28c9a7d82c07.png)
> 
> file won't open ![изображение](https://user-images.githubusercontent.com/71918286/185373319-3760b404-3fff-4cef-b2d8-59a7e2e1b72e.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185373500-37752595-00c7-44fb-9c8f-6dde71fa3f7e.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185373703-d2dfa9bd-29b0-4f53-97c3-dfd91ef7c5e6.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185373789-c485d9bb-856e-4fa6-aa9a-69262fb861f6.png)
> 
> ![изображение](https://user-images.githubusercontent.com/71918286/185373869-7f9e9699-569c-4941-9611-612306b9c84d.png)
> 
> =policy doesn't work
> 
> =report doesn't work
> 
> =userinfo doesn't work
> 
> =userid doesn't work
> 
> =serverinfo doesn't work
> 
> =suggest doesn't work
> 
> music work 50/50
> 
> bot version in package.json "version": "v8.0.0"
> 
> and many other things, maybe I just use an old version of the bot, it seems to me that the bot does not work with discord 14

working on fixes.... gimme a few mins.....

**Comment by Simpleboy353** [comment]
just a few mins... working on fixes....

**Comment by Simpleboy353** [comment]
Applied fixess. the trigger and wasted commands are disabled for now as the error seems to be API related.....

**Comment by makarasty** [comment]
Thanks, I'm glad, I'll go look for more bugs)
