### ISSUE TITLE
The bot doesn't play music

### ISSUE THREAD

**Issue by makarasty** [Simpleboy353/REAPER-2.0#196]
I connect to the channel, start the music with /track play bot enters the voice channel and is silent, no errors in the console

![изображение](https://user-images.githubusercontent.com/71918286/185806544-6e947108-67f3-4748-8783-f9dd5107a1a7.png)

![изображение](https://user-images.githubusercontent.com/71918286/185806599-d2dfe531-ea2d-4d1e-bfb6-559bbcc9b10b.png)

**Comment by Simpleboy353** [comment]
Fixes may take some timeeeee.......

**Comment by Simpleboy353** [comment]
Please try updating discord-player and ytdl-core. Issue seems to be ytdl-core related btw.....
