### ISSUE TITLE
Some commands don't work, +fixes

### ISSUE THREAD

**Issue by makarasty** [Simpleboy353/REAPER-2.0#198]
`` don't work

`=wiki` don't work
`=weather` don't work
`=unlock` don't work

`=mute @user 10s test` crashes the bot, forcing a reboot, use **try**
![изображение](https://user-images.githubusercontent.com/71918286/185808286-b4a7ea01-6b82-44d5-8647-27bd20425263.png)

`=greentext asd` the text is not green
![изображение](https://user-images.githubusercontent.com/71918286/185808367-f7613b93-3541-4b41-bd03-d92a820fb961.png)

`=suggest asd` crashes the bot
![изображение](https://user-images.githubusercontent.com/71918286/185808490-e4a25343-32dc-4ebd-bcfb-ad3ccee88d1e.png)

`=botinfo` add the bot's uptime maybe `message.client.uptime` will work

**Comment by Simpleboy353** [comment]
Fixes may take time as i am engaged with some work....
