### ISSUE TITLE
Error in music module

### ISSUE THREAD

**Issue by srcyberg** [Simpleboy353/REAPER-2.0#212]
![image](https://user-images.githubusercontent.com/123209807/213805580-ab068120-e99d-4a1e-bb6d-faafd0adcb03.png)

Some errors solved .setFooter/.setAuthor -> to v14 but the bot give that error when i try to put 2 songs at the same time

**Comment by Simpleboy353** [comment]
Hey there! I know I am replying very late... but I am working on a new update for the bot, which will most likely fix your errors... Hope this helps!
