### ISSUE TITLE
Msg.edit is not a function

### ISSUE THREAD

**Issue by TheBozzz34** [Simpleboy353/REAPER-2.0#38]
Various commands crash the bot with the exception: `Uncaught Exception: TypeError: msg.edit is not a function` So far it seems to happen with `greentext` and `pp`. Addionally, `ping` fails with a `Cannot send an empty message` error, also `collection.ensureIndex`  is deprecated

**Comment by rodrigoricky** [comment]
When I use the help command, and not using the button, after a few moments, it shows that ms.edit is not a function
