### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by aesovac** [Simpleboy353/REAPER-2.0#47]
Some commands aren't working, like userinfo / mute / etc etc. And sometimes the bot goes automatic offline when someone says a specific command.

**Comment by Simpleboy353** [comment]
> Some commands aren't working, like userinfo / mute / etc etc. And sometimes the bot goes automatic offline when someone says a specific command.

To prevent the bot from going offline:
Go to index.js, go to the error handling part and remove the line `process.exit(1)`

Talking about the commands, if possible can you tell me which commands aren't working, so i can work on it and make some fixes.

**Comment by aesovac** [comment]
,mute ,userinfo ,unmute | I'll test the rest tomorrow so I can tell you what other commands aren't working. Thankyou!

**Comment by Simpleboy353** [comment]
The problem with the image commands won't be fixed for now as I am planning to use a different api for image manipulation. So you may delete the image manipulation commands that don't work.

**Comment by aesovac** [comment]
Alright! And what about the 3 mod commands, is that easy to fix? I tried different codes but I keep getting errors..

**Comment by Simpleboy353** [comment]
> Alright! And what about the 3 mod commands, is that easy to fix? I tried different codes but I keep getting errors..

I am very busy rn so I haven't checked what errors are occurring, so I can't say about that, but usually they are easy to fix.

**Comment by InsufiKoder** [comment]
> Alright! And what about the 3 mod commands, is that easy to fix? I tried different codes but I keep getting errors..

i fixed mute and unmute commands by simply rewriting them, i don't think you need tempmute anymore since now you can assign time in mute command.

**Comment by InsufiKoder** [comment]
Okay you can update the repository and try the command now, should work without any errors.

**Comment by aesovac** [comment]
It's working, thankyou very much! 
Only userinfo is still down. 
The rest is fixed!

**Comment by InsufiKoder** [comment]
> It's working, thankyou very much!
> Only userinfo is still down.
> The rest is fixed!

Oh right, i forgot to check userinfo. I will check the command when i'm available, hope you can wait a bit more.

**Comment by InsufiKoder** [comment]
Well i couldn't fix the userinfo sadly. Developer might have to look to it.

**Comment by aesovac** [comment]
> Well i couldn't fix the userinfo sadly. Developer might have to look to it.

It's alright, I tried different codes but it didn't work.

**Comment by Simpleboy353** [comment]
Thank you @InsufiKoder for fixing the commands!
Talking about the userinfo command, i made some changes to it, haven't tested it yet, but it should work fine.

**Comment by aesovac** [comment]
It's working, thank you all for helping and fixing this together!
