### ISSUE TITLE
Message error

### ISSUE THREAD

**Issue by fomundifr** [Simpleboy353/REAPER-2.0#59]
Good night, because when I only put the prefix of the bot it sends me a message that I should mention to someone? that should not happen when just putting the prefix

**Comment by Simpleboy353** [comment]
can you please explain this a bit more or provide a ss?

**Comment by fomundifr** [comment]
Well what happens is that when for example in my bot the prefix is ​​v? and when using the bot, it works and everything but just putting the prefix without the command this sends me a message that mentions a user.

For instance: 
v?help => It returns the embed with an embed showing me all the commands there are
v? => It returns a message that says: I mentioned a user

**Comment by Simpleboy353** [comment]
Can you try removing aliases from the `mute` and. `unmute` command? I found that there are empty aliases in these two commands and these two could be the causing this issue. If this still doesnt fix you can report here.
