### ISSUE TITLE
Prefix.js command does not work.

### ISSUE THREAD

**Issue by ToonDiscord** [Simpleboy353/REAPER-2.0#6]
First, the command "if (message.member.hasPermission("ADMINISTRATOR")) return message.channel.send(`You don't have the required Permissions!`)" does not work because you're checking if they HAVE the permission, not if they don't. To fix the issue, just put a ! infront of the condition. For example: "if (message.member.hasPermission("ADMINISTRATOR")) return message.channel.send(`You don't have the required Permissions!`)" would turn to "!if (message.member.hasPermission("ADMINISTRATOR")) return message.channel.send(`You don't have the required Permissions!`)". Also, mongoose is outdated. You should switch it to something more compatible. I tried the command and the command does not work.

**Comment by Simpleboy353** [comment]
Fixed
