### ISSUE TITLE
error. How to locate and fix this?

### ISSUE THREAD

**Issue by 1stminhcar** [Simpleboy353/REAPER-2.0#71]
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
      at WebSocketManager.createShards (/home/runner/REAPER-20-2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
      at async Client.login (/home/runner/REAPER-20-2/node_modules/discord.js/src/client/Client.js:245:7) {
    [Symbol(code)]: 'DISALLOWED_INTENTS'
  }
}  reason:  Privileged intent provided is not enabled or whitelisted.
Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'send')
/home/runner/REAPER-20-2/index.js:81
  client.channels.cache.get(ERROR_LOGS_CHANNEL).send({ embeds: [exceptionembed] })
                                               ^

TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (/home/runner/REAPER-20-2/index.js:81:48)
    at process.emit (node:events:390:28)
    at process._fatalException (node:internal/process/execution:170:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! reaper-2.0@7.0.0-stable start: `node index.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the reaper-2.0@7.0.0-stable start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-11T03_15_28_922Z-debug.log

**Comment by 1stminhcar** [comment]
where did you store the intent?

**Comment by 1stminhcar** [comment]
home/runner/REAPER-20-2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/REAPER-20-2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
    at async Client.login (/home/runner/REAPER-20-2/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS' now it get this?

**Comment by Simpleboy353** [comment]
Did you enable Intents for your bot in dev portal?

**Comment by 1stminhcar** [comment]
how?:>

**Comment by 1stminhcar** [comment]
present or server member???

**Comment by Simpleboy353** [comment]
> present or server member???

enable both of these

**Comment by Simpleboy353** [comment]
what error?

**Comment by 1stminhcar** [comment]
uh mongo db again

**Comment by 1stminhcar** [comment]
process.on("uncaughtException", (err) => {
  console.log("Uncaught Exception: " + err);

  const exceptionembed = new MessageEmbed()
  .setTitle("Uncaught Exception")
  .setDescription(`${err}`)
  .setColor("RED")
  client.channels.cache.get(ERROR_LOGS_CHANNEL).send({ embeds: [exceptionembed] })
});



   const rejectionembed = new MessageEmbed()
  .setTitle("Unhandled Promise Rejection")
  .addField("Promise", `${promise}`)
  .addField("Reason", `${reason.message}`)
  .setColor("RED")
  client.channels.cache.get(ERROR_LOGS_CHANNEL).send({ embeds: [rejectionembed] }),
});
